### ISSUE TITLE
Error 403 when trying to Create a DataEventRecord

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNetCoreAngularSignalRSecurity#2]
All signed in, signalR stuff works great, News etc, its awesome.

But when trying to post a DataEventRecord I get nothing. Looking in chrome console I see

![image](https://user-images.githubusercontent.com/9402456/33364755-82676b9c-d531-11e7-9498-619cae8285e5.png)

I have tried when logged in as an admin as well. IS this a bug?

**Comment by damienbod** [comment]
I'll check this, looks like a bug.

**Comment by damienbod** [comment]
fixed
