### ISSUE TITLE
Changes to code in Angular App does not trigger recompile and update to app in browser

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNetCoreAngularSignalRSecurity#4]
Hi There,

Sorry to be hammering you on this repo.

Is there some command that one must run so that webpack will watch for changes and update the app?

I have run the application from visual studio, did not use a task runner or anything. Just ran it using Control F5, and it runs fine, but when you make a change, shut down, re-run it is delivering up the previous code and not the stuff I have changed.

So.... something is wrong. When I go to the task runner in visual studio 2017 I see the Watch - Development task, I try to run it but get this error

![image](https://user-images.githubusercontent.com/9402456/33367974-00f0901a-d53c-11e7-896c-4456d6f296ee.png)

Is there something I am missing?

**Comment by nigel-dewar** [comment]
Update to this.

I found another thread where you were helping a guy out on this

https://github.com/damienbod/AngularWebpackVisualStudio/issues/103

So, there is another Task Runner? Where is this? Is this something one downloads or is it in Visual Studio 2017 by default.?

Is it possible to run task runners from VS, or do you guys run it from CMD windows?

**Comment by damienbod** [comment]
Hi @nigel-dewar 

Use the watch-webpack-dev in the custom menu

Greetings Damien

**Comment by nigel-dewar** [comment]
Awesome thanks i will do this.
