### ISSUE TITLE
Is there a theoretical possibility to log in from the SPA application on a stand alone IdentityServer without redirect?

### ISSUE THREAD

**Issue by Arpanx** [damienbod/AspNetCoreAngularSignalRSecurity#5]
Is there a theoretical possibility to log in from the SPA application on a stand alone IdentityServer without redirect?

**Comment by damienbod** [comment]
yes it is possible, but you leave the application less secure, and don't follow best practices for  authentication, so I would not recommend this. SPA applications should use the OpenID Connect Implicit Flow.
