### ISSUE TITLE
Error when connect from client 

### ISSUE THREAD

**Issue by vietdq1291** [damienbod/AspNetCoreAngularSignalRSecurity#6]
![image](https://user-images.githubusercontent.com/38650722/48880494-5456e300-ee43-11e8-8eb6-cdf2f4cbd9e7.png)

i have error like this when using flow your guide,
can you help me fix that

**Comment by damienbod** [comment]
Hi @vietdq1291 use are using http and 4200, the app is configured to use https and a different port-

Greetings Damien

**Comment by vietdq1291** [comment]
thank you i have fix that now o try join but my username send is null is only have connectionId can you show me how to send username to join invoke

**Comment by damienbod** [comment]
You can register in the STS application
